---
- name: Setup Docker
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      notify:
        - enable docker
        - start docker

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

  handlers:
    - name: enable docker
      systemd:
        name: docker
        enabled: yes

    - name: start docker
      systemd:
        name: docker
        state: started 